/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
  id("application")
  id("org.openjfx.javafxplugin") version "0.0.13"
  `java-library`
  id("edu.sc.seis.launch4j") version "2.5.4"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.apache.derby:derby:10.16.1.1")
    implementation("org.apache.derby:derbyshared:10.15.2.0")
    implementation("org.apache.derby:derbytools:10.15.2.0")
}

javafx {
    version = "19"
    modules("javafx.controls")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

launch4j {
    outfile = "powered-tasks.exe"
    mainClassName = "powered_tasks.App"
}

version = "1.2.1"

application {
    mainClass.set("powered_tasks.App")
}

tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = "powered_tasks.App"
    }
    
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from(sourceSets.main.get().output)
    dependsOn(configurations.runtimeClasspath)
    from({
        configurations.runtimeClasspath.get().filter { it.name.endsWith("jar") }.map { zipTree(it) }
    })
}