/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
  id("application")
  id("org.openjfx.javafxplugin") version "0.0.10"
  `java-library`
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("mysql:mysql-connector-java:8.0.31")
}

javafx {
    sdk = "/libs/javafx-sdk-19"
    modules("javafx.controls", "javafx.fxml")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}

version = "1.2.1"

application {
    mainClass.set("powered_tasks.App")
}